package com.diginori.gymdori;

import io.realm.RealmObject;

public class UserHistory extends RealmObject {
    private String          yyyymmdd;

    // Standard getters & setters generated by your IDE…
    public String getYyyymmdd() { return yyyymmdd; }
    public void   setYyyymmdd(String yyyymmdd) { this.yyyymmdd = yyyymmdd; }
}